#COM CONFIG SERVER
spring:
  application:
    name: soundpro-sound-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ${configServer.serviceId}
      username: ${configServer.username}
      password: ${configServer.password}
      uri: 'http://${configServer.username}:${configServer.password}@${configServer.host}:8888'

configServer:
  serviceId: ${SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID:config-server}
  username: ${CONFIG_SERVER_USERNAME:configserver}
  password: ${CONFIG_SERVER_PASSWORD:1234567}
  host: ${CONFIG_SERVER_HOST:localhost}


      