version: "3.7"
services:
  #service-registry:
  #  image: rafaelsulimann/service-registry:v1
  #  container_name: service-registry
  #  restart: always
  #  ports:
  #    - 8761:8761
  #  networks:
  #    - dev-network
  #config-server:
  #  image: rafaelsulimann/config-server:v1
  #  container_name: config-server
  #  restart: always
  #  ports:
  #     - 8888:8888
  #  environment:
  #    - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=service-registry
  #    - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/rafaelsulimann/soundpro-config-server
  #    - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main
  #    - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=rafaelsulimann
  #    - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=Metallica#357
  #  depends_on:
  #    - service-registry
  #  networks:
  #    - dev-network
  #api-gateway:
  #  image: rafaelsulimann/api-gateway:v2
  #  container_name: api-gateway
  #  restart: always
  #  ports:
  #    - 8080:8080
  #  environment:
  #    - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=service-registry
  #    - CONFIG_SERVER_HOST=config-server
  #  depends_on:
  #    - service-registry
  #    - config-server
  #  networks:
  #    - dev-network
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - dev-network
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dev-network
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: soundpro
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ../mongo-data:/data/db
    networks:
      - dev-network
  sounds:
    image: rafaelsulimann/sounds:v6
    container_name: sounds
    restart: always
    ports:
      - 8081:8081
    environment:
      - KAFKA_NAME=kafka
      - MONGODB_NAME=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=123456
    depends_on:
      - kafka
      - zookeeper
      - mongodb
    networks:
      - dev-network
  # front:
  #   image: soundpro-front:v3
  #   container_name: front
  #   restart: always
  #   ports:
  #     - 5173:5173
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #     - sounds
  #   networks:
  #     - dev-network
networks:
  dev-network:
    driver: bridge